name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - main   # 👈 Deploy every time you push to main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20   # or the version you use
          cache: 'npm'      # or 'npm' if you use npm

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build site
        run: npm run build   # creates the dist/ folder

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
